/** @type {import('tailwindcss').Config} */
const sans = ["Hanken Grotesk", "ui-sans-serif", "system-ui", "Segoe UI", "Roboto", "sans-serif"];
const display = ["Manrope", "ui-sans-serif", "system-ui", "Segoe UI", "Roboto", "sans-serif"];

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#006a39",
        "emerald-vibrant": "#0F9D58",
        "surface-dim": "#d5dcd3",
        "on-tertiary-fixed": "#001f27",
        "on-tertiary-fixed-variant": "#004e5f",
        "inverse-primary": "#64dd91",
        "secondary-fixed-dim": "#a2cde2",
        "secondary-container": "#bde9ff",
        "tertiary-container": "#007f9a",
        "on-primary-fixed": "#00210e",
        "surface-container-low": "#eff6ec",
        "tertiary-fixed-dim": "#4cd6fb",
        "surface-container": "#e9f0e7",
        "surface-container-highest": "#dee4db",
        "surface-variant": "#dee4db",
        "background-warm": "#F8FAFB",
        "on-tertiary-container": "#fafdff",
        "on-primary-container": "#f6fff4",
        "tertiary-fixed": "#b3ebff",
        "on-secondary": "#ffffff",
        background: "#f5fbf2",
        "inverse-on-surface": "#ecf3e9",
        "outline-variant": "#bdcabc",
        "inverse-surface": "#2b322c",
        "on-surface": "#171d18",
        "on-background": "#171d18",
        "success-green": "#2D6A4F",
        "primary-fixed-dim": "#64dd91",
        "surface-container-high": "#e3eae1",
        "primary-container": "#008649",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "teal-accent": "#00818A",
        error: "#ba1a1a",
        surface: "#f5fbf2",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001f2a",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006d3a",
        "on-secondary-container": "#3f6a7c",
        "surface-bright": "#f5fbf2",
        "warning-amber": "#FFB703",
        "on-primary-fixed-variant": "#00522b",
        "secondary-fixed": "#bde9ff",
        outline: "#6d7a6f",
        "navy-deep": "#073B4C",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed": "#82faab",
        "on-secondary-fixed-variant": "#1f4c5d",
        "on-surface-variant": "#3e4a3f",
        tertiary: "#00657a",
        secondary: "#396476",
      },
      fontFamily: {
        sans,
        display,
        body: sans,
        "price-display": display,
        "label-bold": sans,
        "headline-lg": display,
        "body-lg": sans,
        "body-md": sans,
        "headline-md": display,
        "headline-lg-mobile": display,
        "display-lg": display,
        "body-sm": sans,
      },
      fontSize: {
        "price-display": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "margin-mobile": "20px",
        "stack-md": "16px",
        "gutter-desktop": "24px",
        "gutter-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(7, 59, 76, 0.04), 0 4px 16px rgba(7, 59, 76, 0.06)",
        "card-hover": "0 8px 30px rgba(0, 106, 57, 0.14)",
        header: "0 1px 0 rgba(7, 59, 76, 0.06), 0 6px 24px rgba(7, 59, 76, 0.05)",
        drawer: "-16px 0 48px rgba(7, 59, 76, 0.18)",
        pill: "0 2px 8px rgba(0, 106, 57, 0.18)",
      },
      backgroundImage: {
        "hero-mesh":
          "radial-gradient(1200px 500px at 15% -10%, #82faab55, transparent 60%), radial-gradient(900px 500px at 100% 0%, #b3ebff66, transparent 55%)",
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-500px 0" },
          "100%": { backgroundPosition: "500px 0" },
        },
        "pulse-ring": {
          "0%": { boxShadow: "0 0 0 0 rgba(255, 183, 3, 0.5)" },
          "70%": { boxShadow: "0 0 0 12px rgba(255, 183, 3, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(255, 183, 3, 0)" },
        },
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out both",
        "fade-up": "fade-up 0.5s cubic-bezier(0.22, 1, 0.36, 1) both",
        "scale-in": "scale-in 0.25s ease-out both",
        "slide-in-right": "slide-in-right 0.35s cubic-bezier(0.22, 1, 0.36, 1) both",
        shimmer: "shimmer 1.6s linear infinite",
        "pulse-ring": "pulse-ring 2s cubic-bezier(0.66, 0, 0, 1) infinite",
        marquee: "marquee 28s linear infinite",
      },
    },
  },
  plugins: [],
};
